[package]
name = "hypors"
authors = ["Shubhankar Agrawal <shubhankar.a31@gmail.com>"]
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/astronights/hypors"
description = "Hypothesis Testing with Rust"
keywords = ["statistics", "hypothesis", "testing", "data", "p-value"]

[lib]
name = "hypors"
path = "src/lib.rs" 
crate-type = ["cdylib", "lib"]

[dependencies]
serde = {version = ">=1.0.210", features = ["derive"]}
statrs = ">=0.17.1"