[package]
name = "hypors"
version = "0.1.0"
edition = "2021"

[lib]
name = "hypors"
crate-type = ["cdylib", "rlib"]

[dependencies]
statrs = { version = "0.17.1" }
polars = { version = ">=0.43.1", features = ["lazy"]}
pyo3 = { version = "0.22.3", features = ["extension-module"] }