[package]
name = "hypors"
authors = ["Shubhankar Agrawal <shubhankar.a31@gmail.com>"]
version = "0.2.1"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/astronights/hypors"
description = "Hypothesis Testing with Polars"
keywords = ["statistics", "hypothesis", "testing", "data", "p-value"]

[lib]
name = "hypors"
path = "lib.rs" 
crate-type = ["cdylib", "lib"]

[dependencies]
serde = "1.0.210"
statrs = "0.17.1"
polars = "0.43.1"
pyo3 = { version = "0.22.3", features = ["extension-module"], optional = true }

[features]
default = []
python_bindings = ["pyo3"]
